### ISSUE TITLE
v8::Proxy API has changed (V8 6.5.164)

### ISSUE THREAD

**Issue by AlexMasterov** [pinepain/php-v8#93]
Hello! :no_mouth:

v8/v8@5b9adade648b6d4fb717bb0348cdee27d15b6355 ([[proxy] Set [[ProxyTarget]] to null during)

```sh
In file included from /tmp/php-v8/src/php_v8_startup_data.h:24:0,
                 from /tmp/php-v8/src/php_v8_isolate.h:18,
                 from /tmp/php-v8/src/php_v8_context.h:18,
                 from /tmp/php-v8/src/php_v8_exceptions.h:16,
                 from /tmp/php-v8/src/php_v8_value.h:18,
                 from /tmp/php-v8/src/php_v8_proxy.h:16,
                 from /tmp/php-v8/src/php_v8_proxy.cc:17:
/usr/local/v8/include/v8.h: In instantiation of 'v8::Local<T>::Local(v8::Local<S>) [with S = v8::Value; T = v8::Object]':
/tmp/php-v8/src/php_v8_proxy.cc:70:104:   required from here
/usr/local/v8/include/v8.h:167:37: error: invalid conversion from 'v8::Value*' to 'v8::Object*' [-fpermissive]
     *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/usr/local/v8/include/v8.h:213:5: note: in expansion of macro 'TYPE_CHECK'
     TYPE_CHECK(T, S);
     ^~~~~~~~~~
```

**Comment by pinepain** [comment]
@AlexMasterov hi, thanks for reporting. Could you also mention what the step to reproduce the issue? Is it an output in one of tests or you have some crafted script to trigger such output?

**Comment by AlexMasterov** [comment]
@pinepain just try to compile with the V8 version 6.5.164+, it stops at this error.

**Comment by pinepain** [comment]
Oh, I see, make sense 😄. I'll bump v8 min version this week, probably to 6.6.x.

**Comment by pinepain** [comment]
Partially blocked by https://github.com/pinepain/php-v8/issues/95

**Comment by pinepain** [comment]
Another blocker is https://github.com/pinepain/php-v8/issues/99

**Comment by AlexMasterov** [comment]
Thanks for the fix and new release :thumbsup:
